apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/Mutuwa99/argoCD.git
    path: .  
    targetRevision: main
    # helm:
    #   valueFiles:
    #     - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
